baseURL = 'https://kopever.com/'
languageCode = 'en-us'
title = 'Lullaby'
theme = 'paper'
publishdir = '/Users/kopever/Develop/workspace/github/kopstill.github.io'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[params]
  twitter = 'kopstill'
  github = 'kopstill'
  instagram = 'kopstill'
